# Generated by Django 5.1.6 on 2025-02-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('land_area', models.CharField(choices=[('2.5-3.0', '2.5 to 3.0 aana'), ('3.0-3.5', '3.0 to 3.5 aana'), ('3.5-4.0', '3.5 to 4.0 aana'), ('4.0-4.5', '4.0 to 4.5 aana'), ('4.5-5.0', '4.5 to 5.0 aana'), ('> 5.0', 'Greater than 5 aana')], max_length=20)),
                ('ground_coverage', models.FloatField(max_length=50)),
                ('construction_standard', models.CharField(choices=[('affordable', 'Affordable Construction'), ('premium', 'Premium Construction')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajira.district')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='ajira.home')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='ajira.location')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='ajira.district')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajira.municipality'),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_flooring', models.CharField(choices=[('stone', 'Stone'), ('block', 'Block'), ('tile', 'Tile')], default='stone', max_length=50)),
                ('staircase_flooring', models.CharField(choices=[('tile', 'Tile'), ('granite', 'Granite'), ('parquet', 'Parquet'), ('sisou', 'Sisou')], default='tile', max_length=50)),
                ('window_type', models.CharField(choices=[('upvc', 'UPVC'), ('aluminum', 'Aluminum'), ('wood', 'Wood')], default='upvc', max_length=50)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ajira.location')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('bedroom', 'Bedroom'), ('living', 'Living'), ('kitchen', 'Kitchen'), ('dining', 'Dining'), ('bathroom', 'Bathroom'), ('parking', 'Parking'), ('puja', 'Puja Room'), ('laundry', 'Laundry Room'), ('store', 'Store Room')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('flooring_type', models.CharField(choices=[('none', 'None'), ('tile', 'Tile'), ('granite', 'Granite'), ('parquet', 'Parquet'), ('sisou', 'Sisou')], default='none', max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='ajira.floor')),
            ],
        ),
    ]
