# Generated by Django 5.1.6 on 2025-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
