# Generated by Django 5.1.6 on 2025-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0002_summary_total_carpet_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_numm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('bedroom', 'Bedroom'), ('living', 'Living'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('parking', 'Parking'), ('puja', 'Puja Room'), ('laundry', 'Laundry Room'), ('store', 'Store Room')], max_length=50),
        ),
    ]
