# Generated by Django 5.1.6 on 2025-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0002_room_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
